# Setup
title:               Quintec
tagline:             'writeups and other thoughts'
description:         'Hello!'
url:                 http://quintec.github.io
baseurl:             /blog/
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Quintec
  url:               https://quintec.github.io
  email:             quintek55555@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Build settings
markdown: kramdown

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

